version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - bible_data:/var/lib/postgresql/data
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
    networks:
      - bible_network

  api:
    build:
      context: ./api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "5001:5000"
    volumes:
      - ./data/kjv.txt:/app/data/kjv.txt:ro
    depends_on:
      - db
    networks:
      - bible_network

  app:
    build:
      context: ./app
    environment:
      REACT_APP_API_URL: http://localhost:5001
    ports:
      - "3001:3000"
    depends_on:
      - api
    networks:
      - bible_network
  
volumes:
  bible_data:

networks:
  bible_network: